  GNU nano 2.3.1            File: nginx/nginx.conf                              

server {
  listen 80;
  listen [::]:80;

  server_name 54.234.137.213;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://54.234.137.213:3200/;
    proxy_read_timeout 90;
    proxy_redirect http://54.234.137.213:3200/ https://54.234.137.213/;
  }
}


